#OBJS specify the files to compile
# OBJS = main.cpp
OBJS1 = 14-animation.cpp
OBJS2 = main.o globals.o

# compiler name
cc = g++

# compilers flags
COMPILER_FLAGS = -g -w

#sdl2 lib requirement
LIBSDL = `pkg-config --cflags --libs sdl3 sdl3-image`

#linker flags
LINKER_FLAGS = -lSDL3 -lSDL3_image

# OBJ_NAME specifies the target name
OBJ_NAME = game

all : $(OBJ_NAME)

$(OBJ_NAME) : $(OBJS2)
	$(cc) $(OBJS2) $(COMPILER_FLAGS) $(LIBSDL) $(LINKER_FLAGS) -o $(OBJ_NAME)

main.o: main.cpp globals.h
	$(cc) main.cpp $(COMPILER_FLAGS) $(LIBSDL) $(LINKER_FLAGS) -o main.o

globals.o: globals.cpp globals.h
	$(cc) globals.cpp $(COMPILER_FLAGS) $(LIBSDL) $(LINKER_FLAGS) -o globals,o
# DO NOT DELETE
